### ISSUE TITLE
new feature 

### ISSUE THREAD

**Issue by tutucea** [timotejroiko/sweph#14]
please feel free to delete  since its not an actual issue but do you think you can add solcross and mooncross to your code <3   
```
double swe_solcross_ut(

     double x2cross,

double tjd_ut,

int32 iflag,

char *serr);
```

**Comment by timotejroiko** [comment]
these functions are already added, but they are not available in the GPL version since they were added after the licensing changes:

https://github.com/timotejroiko/sweph/blob/main/src/functions/solcross.cpp  
https://github.com/timotejroiko/sweph/blob/main/src/functions/solcross_ut.cpp

**Comment by tutucea** [comment]
silly question but is there an npm package to this ... i tried to take care of it  but i encounter a bunch of errors with my ubuntu version ... which i may fix but it can take some time
