### ISSUE TITLE
SwissEph file 'sepl_18.se1' not found in PATH

### ISSUE THREAD

**Issue by FedorovD** [timotejroiko/sweph#21]
After some bumping of package versions in the project, the instance started stopping without any errors in the console. After some research, I found this happening when I do calculations through the sweph module. There are no such stopped locally, but the calculations have become incorrect, this is what I get in the calculation of the planet's ramc and decl:
<img width="671" alt="image" src="https://github.com/timotejroiko/sweph/assets/15704475/544a61a9-7a89-413d-8977-ca960d6c0c56">

**Comment by timotejroiko** [comment]
hello, are you using the `set_ephe_path()` function?

**Comment by FedorovD** [comment]
> hello, are you using the `set_ephe_path()` function?

Thx!
