### ISSUE TITLE
Electronjs

### ISSUE THREAD

**Issue by krishnaguragain** [timotejroiko/sweph#5]
Will this work with electronjs for mac apps?

**Comment by krisztianb** [comment]
If you install this Node.js package it gets compiled on your local system. Therefore the output (binary) is created for your particular system. You can forge it into your ElectronJs application like so: https://stackoverflow.com/questions/38361996/how-can-i-bundle-a-precompiled-binary-with-electron/

But it will only work on systems like yours and not cross platform.

**Comment by timotejroiko** [comment]
i have not tested it with mac or electron but it should work

**Comment by timotejroiko** [comment]
to close this issue, Electron supports native node addons as long as they are compiled properly for Electron, take a look at their guide: https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules

Im gonna go ahead and close this, let me know if any changes!
