### ISSUE TITLE
Error in house_name() method

### ISSUE THREAD

**Issue by bizprat** [timotejroiko/sweph#7]
Method: house_name() asks for a string as a parameter, but gives an error when passed as house_name('p').

When an integer is passed like house_name(1), it works. But gives the same output for all other integer values.

**Comment by timotejroiko** [comment]
hey, im currently travelling, i will look into it soon

**Comment by timotejroiko** [comment]
thank you for the patience, the issue should be fixed now!

**Comment by bizprat** [comment]
Thanks I will check it
